build:
  image: node:argon
  commands:
    - echo "ok"
publish:
  ecr:
    access_key: $$DRONE_CI_ACCESS_KEY
    secret_key: $$DRONE_CI_SECRET_KEY
    region: us-west-2
    repo: lab-test
    tag:
      - dummyservice
      - latest
    storage_driver: vfs
  ecs:
    access_key: $$DRONE_CI_ACCESS_KEY
    secret_key: $$DRONE_CI_SECRET_KEY
    region: eu-west-2
    image_name: lab-test
    image_tag: dummyservice
    service: test-svc
    port_mappings:
      - 3000 9000
    memory: 128
compose:
  mongo:
    image: mongo:3.2
